// ENGRAM CYOA DATA v1
// 数据存档：导入时仅解析 JSON，不执行脚本。
window.ENGRAM_PROJECT = {
  "schema": "engram-cyoa",
  "version": 1,
  "id": "stellagram-default-v4",
  "meta": {
    "title": "随星录",
    "subtitle": "STELLAGRAM OF WHIMSIES",
    "kicker": "ENGRAM / INITIAL CONDITIONS",
    "edition": "0.5",
    "author": "",
    "intro": "你在一段无法追溯来源的日志里醒来。世界仍在运行，历史仍在向前；只有你的记录多出了一行本不该存在的校验信息。\n\n桌上留着一份空白档案，以及 **50 枚铟锭**。每一次选择，都将在下一页留下痕迹。",
    "rules": "初始持有 **50 IN**。正值增加铟锭，负值消耗铟锭；完成构筑时，余额不得低于 0。\n\n世界状态、起始权限与存在分辨率各选一项；四项基础素质各选一档。自选 Tag 与路线可以多选，但应满足各自的前置与互斥条件。",
    "footer": "STELLAGRAM OF WHIMSIES",
    "notes": "铟锭 / IN（Ingot）。代币名称、初始持有量与各项变化均可在项目中修改。\nH 级统称象胥 / Haltija；四大机关分支后置展示。",
    "tokenName": "铟锭",
    "tokenSymbol": "IN",
    "initial": 50,
    "brand": "stellagram",
    "logo": {
      "light": {
        "src": "",
        "name": "",
        "alt": "",
        "caption": "",
        "credit": "",
        "ratio": "1/1",
        "fit": "cover",
        "x": 50,
        "y": 50,
        "show": true
      },
      "dark": {
        "src": "",
        "name": "",
        "alt": "",
        "caption": "",
        "credit": "",
        "ratio": "1/1",
        "fit": "cover",
        "x": 50,
        "y": 50,
        "show": true
      },
      "align": "left",
      "width": 430,
      "showSubtitle": true
    },
    "labels": {
      "initial": "INDIUM / INVENTORY",
      "image": "IMAGE / RESERVED",
      "end": "END OF RECORD",
      "record": "RECORD / 049",
      "decor": "",
      "single": "单选",
      "multi": "多选",
      "display": "展示",
      "attribute": "每行单选",
      "text": "自由文本"
    },
    "created": "2026-09-05T21:11:46.145Z",
    "modified": "2026-09-05T21:45:35.761Z",
    "image": {
      "src": "",
      "name": "",
      "alt": "",
      "caption": "",
      "credit": "",
      "ratio": "16/9",
      "fit": "cover",
      "x": 50,
      "y": 50,
      "show": false
    }
  },
  "theme": {
    "mode": "light",
    "accent": "#8267A6",
    "gold": "#5D789D",
    "positive": "#527E6F",
    "negative": "#CA8790",
    "background": "#F1F0ED",
    "surface": "#FAF9F6",
    "text": "#25272B",
    "muted": "#63666C",
    "font": "rajdhani",
    "bodySize": 20,
    "cardTitleSize": 28,
    "moduleTitleSize": 36,
    "wear": 0,
    "titleSize": 64,
    "width": 1440,
    "gap": 24,
    "radius": 2,
    "grid": true,
    "placeholders": true,
    "showStatus": false,
    "showRules": true,
    "showDecor": true,
    "showFooter": true
  },
  "output": {
    "moduleNumbers": false,
    "moduleTitles": true,
    "moduleSubtitles": true,
    "selectionHints": true,
    "cardNumbers": false,
    "attributeTitles": true,
    "pageLabels": true
  },
  "settings": {
    "enforceBudget": false,
    "showLocked": false
  },
  "modules": [
    {
      "id": "world",
      "title": "世界状态",
      "subtitle": "WORLD STATE",
      "description": "决定这条潜图的大尺度环境。",
      "type": "choices",
      "selection": "single",
      "required": true,
      "min": 0,
      "max": 0,
      "columns": 5,
      "image": {
        "src": "",
        "name": "",
        "alt": "",
        "caption": "",
        "credit": "",
        "ratio": "16/9",
        "fit": "cover",
        "x": 50,
        "y": 50,
        "show": false
      },
      "layout": "grid",
      "visibility": "public",
      "unlock": [],
      "unlockMode": "all",
      "display": {
        "moduleNumbers": true,
        "moduleTitles": true,
        "moduleSubtitles": true,
        "selectionHints": true,
        "cardNumbers": false,
        "attributeTitles": true
      },
      "headings": [],
      "notes": "",
      "text": "",
      "textStyle": "plain",
      "input": false,
      "inputLabel": "你的记录",
      "cards": [
        {
          "id": "world-collapse",
          "title": "潮汐失稳",
          "subtitle": "SYSTEMIC COLLAPSE",
          "description": "海侵、能源与地缘冲突同时恶化，泛南秩序难以维持。大量系统性风险叠加。",
          "points": 50,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "world-dawn",
          "title": "灰色黎明",
          "subtitle": "GREY DAWN",
          "description": "独立战争与权力重组尚未结束。资源紧张，组织边界模糊，但新的秩序正在形成。",
          "points": 25,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "world-2039",
          "title": "基准潜图 · 2039",
          "subtitle": "REFERENCE HYPOGRAM",
          "description": "以主体故事时期为参考：泛南联邦初定，元素天演仍以隐蔽方式运行。",
          "points": 0,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "world-stable",
          "title": "极地秩序",
          "subtitle": "POLAR STABILITY",
          "description": "联邦制度与国际关系相对稳定，基础设施恢复，公开冲突显著减少。",
          "points": -25,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "world-stars",
          "title": "星海前夜",
          "subtitle": "PRELUDE TO THE STARS",
          "description": "深空工程与跨世界研究进入常态，人类拥有更高的总体安全余量。",
          "points": -50,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        }
      ],
      "rows": []
    },
    {
      "id": "status",
      "title": "身份与权限",
      "subtitle": "STATUS / ACCESS",
      "description": "描述你在社会系统中的起始便利度，不等同于图录分辨率。",
      "type": "choices",
      "selection": "single",
      "required": true,
      "min": 0,
      "max": 0,
      "columns": 5,
      "image": {
        "src": "",
        "name": "",
        "alt": "",
        "caption": "",
        "credit": "",
        "ratio": "16/9",
        "fit": "cover",
        "x": 50,
        "y": 50,
        "show": false
      },
      "layout": "grid",
      "visibility": "public",
      "unlock": [],
      "unlockMode": "all",
      "display": {
        "moduleNumbers": true,
        "moduleTitles": true,
        "moduleSubtitles": true,
        "selectionHints": true,
        "cardNumbers": false,
        "attributeTitles": true
      },
      "headings": [],
      "notes": "",
      "text": "",
      "textStyle": "plain",
      "input": false,
      "inputLabel": "你的记录",
      "cards": [
        {
          "id": "status-none",
          "title": "无籍之人",
          "subtitle": "UNREGISTERED",
          "description": "缺少稳定身份与制度保护，很多基础服务都需要绕行灰色渠道。",
          "points": 40,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "status-edge",
          "title": "外围居民",
          "subtitle": "PERIPHERAL",
          "description": "合法存在，但资源、交通与信息权限都很有限。",
          "points": 20,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "status-citizen",
          "title": "普通公民",
          "subtitle": "CITIZEN",
          "description": "拥有正常身份、教育与就业路径，没有额外的制度性特权。",
          "points": 0,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "status-pro",
          "title": "专业机构成员",
          "subtitle": "INSTITUTIONAL",
          "description": "你已经进入大学、研究机构、工业系统或同等级专业网络。",
          "points": -20,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "status-high",
          "title": "高位权限持有者",
          "subtitle": "HIGH ACCESS",
          "description": "能够接触战略资源、封闭档案或高等级行政系统；相应地也更难置身事外。",
          "points": -40,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        }
      ],
      "rows": []
    },
    {
      "id": "resolution",
      "title": "存在分辨率",
      "subtitle": "RESOLUTION",
      "description": "这是系统如何记录你的层级，不等同于职业或能力值。",
      "type": "choices",
      "selection": "single",
      "required": true,
      "min": 0,
      "max": 0,
      "columns": 4,
      "image": {
        "src": "",
        "name": "",
        "alt": "",
        "caption": "",
        "credit": "",
        "ratio": "16/9",
        "fit": "cover",
        "x": 50,
        "y": 50,
        "show": false
      },
      "layout": "grid",
      "visibility": "public",
      "unlock": [],
      "unlockMode": "all",
      "display": {
        "moduleNumbers": true,
        "moduleTitles": true,
        "moduleSubtitles": true,
        "selectionHints": true,
        "cardNumbers": false,
        "attributeTitles": true
      },
      "headings": [],
      "notes": "",
      "text": "",
      "textStyle": "plain",
      "input": false,
      "inputLabel": "你的记录",
      "cards": [
        {
          "id": "res-p",
          "title": "P · 常量",
          "subtitle": "P-ZOMBIE / CONSTANT",
          "description": "系统把你视作维持世界连续性的常量。作为玩家选择这一项，本身就构成一个值得追问的悖论。",
          "points": 35,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "res-d",
          "title": "D · 哑变量",
          "subtitle": "DUMMY VARIABLE",
          "description": "你与关键元变量高度绑定，在重大事件里有稳定权重，但自主跨图能力有限。",
          "points": 15,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "res-m",
          "title": "M · 元变量",
          "subtitle": "META-VARIABLE",
          "description": "标准觉醒变量：拥有完整的个体一致性，并可能在不同图录之间留下可追踪记录。",
          "points": 0,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "res-h",
          "title": "H · 象胥",
          "subtitle": "HALTIJA",
          "description": "H 级象胥。你已具备介入图录运行的资格，具体职能取决于你所接触的机关。",
          "points": -70,
          "status": "ready",
          "badge": "H",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        }
      ],
      "rows": []
    },
    {
      "id": "attributes",
      "title": "基础素质",
      "subtitle": "ATTRIBUTES",
      "description": "",
      "type": "attributes",
      "selection": "single",
      "required": false,
      "min": 0,
      "max": 0,
      "columns": 5,
      "image": {
        "src": "",
        "name": "",
        "alt": "",
        "caption": "",
        "credit": "",
        "ratio": "16/9",
        "fit": "cover",
        "x": 50,
        "y": 50,
        "show": false
      },
      "layout": "grid",
      "visibility": "public",
      "unlock": [],
      "unlockMode": "all",
      "display": {
        "moduleNumbers": true,
        "moduleTitles": true,
        "moduleSubtitles": true,
        "selectionHints": true,
        "cardNumbers": false,
        "attributeTitles": true
      },
      "headings": [],
      "notes": "",
      "text": "",
      "textStyle": "plain",
      "input": false,
      "inputLabel": "你的记录",
      "cards": [],
      "rows": [
        {
          "id": "attr-body",
          "title": "体格",
          "description": "身体条件与长期训练水平。",
          "required": true,
          "cards": [
            {
              "id": "body-1",
              "title": "羸弱",
              "subtitle": "FRAGILE",
              "description": "长期高强度行动对你并不友好。",
              "points": 30,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            },
            {
              "id": "body-2",
              "title": "略有欠缺",
              "subtitle": "BELOW AVG.",
              "description": "日常无碍，连续奔跑、负重或低温环境会很吃力。",
              "points": 10,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            },
            {
              "id": "body-3",
              "title": "普通",
              "subtitle": "NORMAL",
              "description": "一个正常健康人的基线。",
              "points": 0,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            },
            {
              "id": "body-4",
              "title": "训练有素",
              "subtitle": "TRAINED",
              "description": "拥有稳定运动习惯或专业体能训练。",
              "points": -10,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            },
            {
              "id": "body-5",
              "title": "人类极限",
              "subtitle": "PEAK HUMAN",
              "description": "在不引入超自然强化的前提下逼近人类体能上限。",
              "points": -30,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            }
          ]
        },
        {
          "id": "attr-knowledge",
          "title": "学识",
          "description": "科研、工程与专业训练的综合基线。",
          "required": true,
          "cards": [
            {
              "id": "know-1",
              "title": "门外汉",
              "subtitle": "OUTSIDER",
              "description": "面对专业系统时需要从头学习。",
              "points": 30,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            },
            {
              "id": "know-2",
              "title": "基础薄弱",
              "subtitle": "BASIC",
              "description": "知道概念，但很难独立处理复杂问题。",
              "points": 10,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            },
            {
              "id": "know-3",
              "title": "专业训练",
              "subtitle": "TRAINED",
              "description": "完成系统性的高等教育或同等级训练。",
              "points": 0,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            },
            {
              "id": "know-4",
              "title": "领域专家",
              "subtitle": "SPECIALIST",
              "description": "能独立承担高难度专业工作。",
              "points": -10,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            },
            {
              "id": "know-5",
              "title": "跨域怪物",
              "subtitle": "POLYMATH",
              "description": "在多个高门槛领域都保持异常强的学习与迁移能力。",
              "points": -30,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            }
          ]
        },
        {
          "id": "attr-adapt",
          "title": "应变",
          "description": "面对未知、冲突与系统故障时的临场表现。",
          "required": true,
          "cards": [
            {
              "id": "adapt-1",
              "title": "慢半拍",
              "subtitle": "LAG",
              "description": "意外往往先发生，你再开始理解发生了什么。",
              "points": 30,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            },
            {
              "id": "adapt-2",
              "title": "稍显生涩",
              "subtitle": "HESITANT",
              "description": "能处理小问题，但复杂危机容易打乱节奏。",
              "points": 10,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            },
            {
              "id": "adapt-3",
              "title": "临场正常",
              "subtitle": "NORMAL",
              "description": "普通人的合理反应速度。",
              "points": 0,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            },
            {
              "id": "adapt-4",
              "title": "反应敏锐",
              "subtitle": "SHARP",
              "description": "能很快识别优先级并执行。",
              "points": -10,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            },
            {
              "id": "adapt-5",
              "title": "危机处理器",
              "subtitle": "INCIDENT CORE",
              "description": "越混乱的局面，你反而越接近自己的最佳状态。",
              "points": -30,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            }
          ]
        },
        {
          "id": "attr-luck",
          "title": "运势",
          "description": "把无法归因于能力与信息的剩余部分交给概率。",
          "required": true,
          "cards": [
            {
              "id": "luck-1",
              "title": "厄运缠身",
              "subtitle": "CURSED",
              "description": "低概率事故似乎总能找到你。",
              "points": 30,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            },
            {
              "id": "luck-2",
              "title": "偏衰",
              "subtitle": "UNLUCKY",
              "description": "统计结果总比预期稍差一点。",
              "points": 10,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            },
            {
              "id": "luck-3",
              "title": "概率学正常",
              "subtitle": "EXPECTED",
              "description": "大数定律终于愿意正常工作。",
              "points": 0,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            },
            {
              "id": "luck-4",
              "title": "好运连连",
              "subtitle": "FORTUNATE",
              "description": "关键时刻常能撞上相对有利的结果。",
              "points": -10,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            },
            {
              "id": "luck-5",
              "title": "观测者偏爱？",
              "subtitle": "OBSERVER BIAS?",
              "description": "巧合已经多到值得怀疑是否有人在后台替你重抽。",
              "points": -30,
              "status": "ready",
              "badge": "",
              "span": 1,
              "image": {
                "src": "",
                "name": "",
                "alt": "",
                "caption": "",
                "credit": "",
                "ratio": "1/1",
                "fit": "cover",
                "x": 50,
                "y": 50,
                "show": true
              },
              "visibility": "public",
              "unlock": [],
              "unlockMode": "all",
              "requires": [],
              "excludes": [],
              "notes": "",
              "fields": []
            }
          ]
        }
      ]
    },
    {
      "id": "canon",
      "title": "核心设定",
      "subtitle": "CANON TAGS",
      "description": "直接改变你与元素天演、图录机制或世界底层规则的关系。",
      "type": "choices",
      "selection": "multi",
      "required": false,
      "min": 0,
      "max": 0,
      "columns": 4,
      "image": {
        "src": "",
        "name": "",
        "alt": "",
        "caption": "",
        "credit": "",
        "ratio": "16/9",
        "fit": "cover",
        "x": 50,
        "y": 50,
        "show": false
      },
      "layout": "grid",
      "visibility": "public",
      "unlock": [],
      "unlockMode": "all",
      "display": {
        "moduleNumbers": false,
        "moduleTitles": false,
        "moduleSubtitles": false,
        "selectionHints": false,
        "cardNumbers": false,
        "attributeTitles": true
      },
      "headings": [
        {
          "id": "head-canon",
          "title": "自选 Tag",
          "subtitle": "MARKS LEFT ON THE WORLD",
          "before": "start",
          "align": "center",
          "size": 34,
          "spacing": 22
        }
      ],
      "notes": "",
      "text": "",
      "textStyle": "plain",
      "input": false,
      "inputLabel": "你的记录",
      "cards": [
        {
          "id": "tag-element",
          "title": "空席元素使",
          "subtitle": "VACANT ELEMENT",
          "description": "你取得一个当前未被占用的元素席位。具体元素与能力仍需另行填写。",
          "points": -30,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "tag-artifact",
          "title": "元素信物",
          "subtitle": "ELEMENT ARTIFACT",
          "description": "你持有一个可被元素体系识别的信物。它的归属、强化幅度与代价由后续设定决定。",
          "points": -15,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "tag-sense",
          "title": "感应过强",
          "subtitle": "OVER-SENSING",
          "description": "你更容易发现相近元素的存在，同时也更难把自己从别人的感应中隐藏。",
          "points": 10,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "tag-anchor",
          "title": "锚点异常损耗",
          "subtitle": "ANCHOR DRAIN",
          "description": "你的高强度异常行为会更明显地反映到锚点负荷上。",
          "points": 25,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "tag-record",
          "title": "档案重影",
          "subtitle": "DOUBLE RECORD",
          "description": "同一套系统里出现了两份都能通过校验的个人档案。没有人知道哪份才是“先来的”。",
          "points": 20,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "tag-edge",
          "title": "世界边缘既视感",
          "subtitle": "EDGE DÉJÀ VU",
          "description": "你偶尔会看见渲染错误、重复街景或不该出现的系统式提示。",
          "points": 10,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        }
      ],
      "rows": []
    },
    {
      "id": "worldtags",
      "title": "其他设定",
      "subtitle": "WORLD TAGS",
      "description": "改变社会与历史背景的宏观开关。",
      "type": "choices",
      "selection": "multi",
      "required": false,
      "min": 0,
      "max": 0,
      "columns": 3,
      "image": {
        "src": "",
        "name": "",
        "alt": "",
        "caption": "",
        "credit": "",
        "ratio": "16/9",
        "fit": "cover",
        "x": 50,
        "y": 50,
        "show": false
      },
      "layout": "grid",
      "visibility": "public",
      "unlock": [],
      "unlockMode": "all",
      "display": {
        "moduleNumbers": true,
        "moduleTitles": true,
        "moduleSubtitles": true,
        "selectionHints": true,
        "cardNumbers": false,
        "attributeTitles": true
      },
      "headings": [],
      "notes": "",
      "text": "",
      "textStyle": "plain",
      "input": false,
      "inputLabel": "你的记录",
      "cards": [
        {
          "id": "wt-public",
          "title": "天演公开化",
          "subtitle": "ELEMENTS EXPOSED",
          "description": "元素使不再只是秘密档案，各组织开始公开争夺与监管。",
          "points": 30,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "wt-lockdown",
          "title": "南极封锁",
          "subtitle": "POLAR LOCKDOWN",
          "description": "出入境、通讯与物流受到长期限制。",
          "points": 20,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "wt-bios",
          "title": "模世界普及",
          "subtitle": "BIOS EVERYWHERE",
          "description": "意识上传与模世界服务已经进入普通人的生活。",
          "points": -20,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "wt-expedition",
          "title": "大远征提前",
          "subtitle": "EARLY EXPEDITION",
          "description": "深空航行计划更早获得资源与政治优先级。",
          "points": -15,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "wt-monazite",
          "title": "独居石供应稳定",
          "subtitle": "MONAZITE STABLE",
          "description": "能源体系获得更高安全余量，社会波动随之下降。",
          "points": -15,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "wt-para",
          "title": "异图干涉增加",
          "subtitle": "PARAGRAM BLEED",
          "description": "平行实例之间的痕迹更频繁地泄漏到当前世界。",
          "points": 25,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        }
      ],
      "rows": []
    },
    {
      "id": "personal",
      "title": "特殊设定",
      "subtitle": "PERSONAL TAGS",
      "description": "个人身份、组织关系与无法归入基础参数的特殊状态。",
      "type": "choices",
      "selection": "multi",
      "required": false,
      "min": 0,
      "max": 0,
      "columns": 4,
      "image": {
        "src": "",
        "name": "",
        "alt": "",
        "caption": "",
        "credit": "",
        "ratio": "16/9",
        "fit": "cover",
        "x": 50,
        "y": 50,
        "show": false
      },
      "layout": "grid",
      "visibility": "public",
      "unlock": [],
      "unlockMode": "all",
      "display": {
        "moduleNumbers": true,
        "moduleTitles": true,
        "moduleSubtitles": true,
        "selectionHints": true,
        "cardNumbers": false,
        "attributeTitles": true
      },
      "headings": [],
      "notes": "",
      "text": "",
      "textStyle": "plain",
      "input": false,
      "inputLabel": "你的记录",
      "cards": [
        {
          "id": "pt-cua",
          "title": "CUA 关系",
          "subtitle": "CONTINENTAL UNIVERSITY",
          "description": "你与南极洲立大学存在稳定的学习、研究或工作关系。",
          "points": 0,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "pt-luacl",
          "title": "LUACL 知道你的名字",
          "subtitle": "LAWRENCE D'URVILLE",
          "description": "你能更容易接触核心科研资源；相应地，核心科研资源也更容易接触你。",
          "points": 20,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "pt-wui",
          "title": "WUI 工业网络",
          "subtitle": "WEDDELL UNITED",
          "description": "你拥有稳定的工业系统与企业渠道。",
          "points": 5,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "pt-tia",
          "title": "冰原同盟会网络",
          "subtitle": "ICEFIELD ALLIANCE",
          "description": "你能使用一部分底层社会的安全屋、运输与消息渠道。",
          "points": 10,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "pt-pasc",
          "title": "PASC 高层关系",
          "subtitle": "SCIENCE COUNCIL",
          "description": "你能够直接触及泛南权力中心，但每个请求也会留下更深的记录。",
          "points": -35,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "pt-apeiron",
          "title": "Apëiron 接口",
          "subtitle": "APEIRON",
          "description": "你获得一条来自天平论体系的高权限技术接口。它的善意程度暂不保证。",
          "points": -20,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "pt-juno",
          "title": "Juno 看见你了",
          "subtitle": "JUNO SAW YOU",
          "description": "某次查询结束后，后台留下了一条无法复现的访问记录。她目前什么也没有做。",
          "points": 0,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "pt-refugee",
          "title": "海侵遗民",
          "subtitle": "DISPLACED",
          "description": "你的旧居或故乡已经因海侵而失去，身份与家庭网络因此发生长期断裂。",
          "points": 10,
          "status": "ready",
          "badge": "",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        }
      ],
      "rows": []
    },
    {
      "id": "scenarios",
      "title": "大型路线",
      "subtitle": "SCENARIOS",
      "description": "",
      "type": "scenario",
      "selection": "multi",
      "required": false,
      "min": 0,
      "max": 0,
      "columns": 1,
      "image": {
        "src": "",
        "name": "",
        "alt": "",
        "caption": "",
        "credit": "",
        "ratio": "16/9",
        "fit": "cover",
        "x": 50,
        "y": 50,
        "show": false
      },
      "layout": "grid",
      "visibility": "public",
      "unlock": [],
      "unlockMode": "all",
      "display": {
        "moduleNumbers": true,
        "moduleTitles": true,
        "moduleSubtitles": true,
        "selectionHints": true,
        "cardNumbers": false,
        "attributeTitles": true
      },
      "headings": [],
      "notes": "",
      "text": "",
      "textStyle": "plain",
      "input": false,
      "inputLabel": "你的记录",
      "cards": [
        {
          "id": "sc-grey",
          "title": "灰色黎明：余波",
          "subtitle": "GREY DAWN / AFTERMATH",
          "description": "你被卷入泛南政权建立前后的高风险过渡期。胜利并不会自动带来秩序。",
          "points": 25,
          "status": "ready",
          "badge": "ROUTE",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": [
            {
              "label": "目标",
              "value": "在独立战争余波与权力重组中维持自己的生存与立场。"
            },
            {
              "label": "结果",
              "value": "由你的选择决定进入联邦、离开南极，或转入其他组织路线。"
            }
          ]
        },
        {
          "id": "sc-evolve",
          "title": "元素天演：激活",
          "subtitle": "ELEMENTAL EXPERIMENT",
          "description": "筛选程序进入高活跃状态。原本可以互相回避的元素使开始被同一套机制推向交汇点。",
          "points": 35,
          "status": "ready",
          "badge": "ROUTE",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": [
            {
              "label": "目标",
              "value": "在不被筛选机制彻底定义的情况下找到自己的行动方式。"
            },
            {
              "label": "结果",
              "value": "可能解锁更高等级的元素关系、管理员线索或异图信息。"
            }
          ]
        },
        {
          "id": "sc-check",
          "title": "CHECKSUM MISMATCH",
          "subtitle": "FILE / IDENTITY ERROR",
          "description": "陵墓后台认为你“既存在，又不应当存在”。从这一刻起，身份问题会变成一条真正的剧情主线。",
          "points": 50,
          "status": "ready",
          "badge": "ROUTE",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": [
            {
              "label": "目标",
              "value": "查清发生冲突的是记忆、身份、世界线，还是整个图录层级。"
            },
            {
              "label": "结果",
              "value": "可能打开异图、间图或管理权限相关路线。"
            }
          ]
        }
      ],
      "rows": []
    },
    {
      "id": "haltija",
      "title": "象胥分岔",
      "subtitle": "HALTIJA / FOUR APPARATUSES",
      "description": "四种职能均属于 H 级，彼此没有行政上下级关系。",
      "type": "choices",
      "selection": "single",
      "required": true,
      "min": 0,
      "max": 0,
      "columns": 4,
      "image": {
        "src": "",
        "name": "",
        "alt": "",
        "caption": "",
        "credit": "",
        "ratio": "16/9",
        "fit": "cover",
        "x": 50,
        "y": 50,
        "show": false
      },
      "layout": "grid",
      "visibility": "gated",
      "unlock": [
        "res-h"
      ],
      "unlockMode": "all",
      "display": {
        "moduleNumbers": true,
        "moduleTitles": true,
        "moduleSubtitles": true,
        "selectionHints": true,
        "cardNumbers": false,
        "attributeTitles": true
      },
      "headings": [],
      "notes": "",
      "text": "",
      "textStyle": "plain",
      "input": false,
      "inputLabel": "你的记录",
      "cards": [
        {
          "id": "h-maus",
          "title": "墓守",
          "subtitle": "MAUSOLEUM",
          "description": "对应陵墓：负责向潜图方向的封存、运行与管理。",
          "points": 0,
          "status": "ready",
          "badge": "H",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "h-para",
          "title": "庭师",
          "subtitle": "PARADEISOS",
          "description": "对应悬苑：负责向上位层级的读取、解算与实体化。",
          "points": 0,
          "status": "ready",
          "badge": "H",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "h-kale",
          "title": "镜匠",
          "subtitle": "KALEIDOSCOPE",
          "description": "对应万华镜：负责异图之间的折射、观测与连接。",
          "points": 0,
          "status": "ready",
          "badge": "H",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        },
        {
          "id": "h-sarc",
          "title": "艄公",
          "subtitle": "SARCOPHAGUS",
          "description": "对应石棺：负责间图中的潜航、承载与意识保护。",
          "points": 0,
          "status": "ready",
          "badge": "H",
          "span": 1,
          "image": {
            "src": "",
            "name": "",
            "alt": "",
            "caption": "",
            "credit": "",
            "ratio": "1/1",
            "fit": "cover",
            "x": 50,
            "y": 50,
            "show": true
          },
          "visibility": "public",
          "unlock": [],
          "unlockMode": "all",
          "requires": [],
          "excludes": [],
          "notes": "",
          "fields": []
        }
      ],
      "rows": []
    },
    {
      "id": "notes",
      "title": "构筑笔记",
      "subtitle": "FIELD NOTES",
      "description": "",
      "type": "text",
      "selection": "single",
      "required": false,
      "min": 0,
      "max": 0,
      "columns": 3,
      "image": {
        "src": "",
        "name": "",
        "alt": "",
        "caption": "",
        "credit": "",
        "ratio": "16/9",
        "fit": "cover",
        "x": 50,
        "y": 50,
        "show": false
      },
      "layout": "grid",
      "visibility": "public",
      "unlock": [],
      "unlockMode": "all",
      "display": {
        "moduleNumbers": true,
        "moduleTitles": true,
        "moduleSubtitles": true,
        "selectionHints": true,
        "cardNumbers": false,
        "attributeTitles": true
      },
      "headings": [],
      "notes": "",
      "text": "在这里写下你的出生地、具体元素、组织关系，以及仍未履行的约定。",
      "textStyle": "plain",
      "input": true,
      "inputLabel": "为这次开局留下记录",
      "cards": [],
      "rows": []
    }
  ],
  "play": {
    "selected": [],
    "answers": {},
    "name": "",
    "note": ""
  }
};
